name: Trivy SCA Scan

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.69.7
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          output: 'trivy-results.txt'
          severity: 'LOW,MEDIUM,HIGH,CRITICAL'
          ignore-unfixed: false
          exit-code: '0'

      - name: Show Trivy results
        run: cat trivy-results.txt
